### ISSUE TITLE
Example code does not work for me - @Nonnull is part of gwt-dev dependency which is not a "real" gwt dependency

### ISSUE THREAD

**Issue by heptetgroup** [realityforge/gwt-websockets#5]
gwt-dev is not meant to be a dependency of gwt projects to compile, so @Nonnull is not available to my application. compilation succeeds when i remove the annotation

**Comment by realityforge** [comment]
If you look at the https://github.com/realityforge/gwt-websockets/blob/master/build.yaml file you will see that gwt-dev is not included and in fact the dependency where it comes from is `com.google.code.findbugs:jsr305:jar:2.0.1`. Thanks for the heads up!

**Comment by heptetgroup** [comment]
I guess what I mean is that the example code on the front page doesn't seem to compile for me, that's all.

**Comment by realityforge** [comment]
Your right - I have just u[dated the example to remove the @Nonnull annotation - thanks!

**Comment by heptetgroup** [comment]
Thank you for your work on this - works great for me and its much appreciated.
