### ISSUE TITLE
Cant resolve "Nonnull" annotation

### ISSUE THREAD

**Issue by Didi95** [realityforge/gwt-websockets#7]
I tried to use the library with gwt-2.8 and ran into that issue: 
 [ERROR] Line 7: The import javax.annotation.Nullable cannot be resolved

It seems that gwt have removed this dependency from the gwt project, so you have to add it [manually](https://github.com/gwtproject/gwt/issues/9382). 

I tried it but it didnt worked for me....

**Comment by Didi95** [comment]
GWT: 2.8.1
websocket lib version: 1.2

using the GWT GIN modul system. library is imported and found in the classpath, the Nonnull check seems to be the only one that fails....anyone have an idea for a workaround?

**Comment by realityforge** [comment]
The solution is to add the dependency manually. I am not sure why it did not work for you. You can add any dependency that supplies `@Nonnull` to your compiler. I think you will probably need a dependency like the following. The binary for the javac compiler and the "sources" classifier for GWT.

```xml
<dependency>
  <groupId>com.google.code.findbugs</groupId>
  <artifactId>jsr305</artifactId>
  <version>3.0.0</version>
</dependency>
<dependency>
  <groupId>com.google.code.findbugs</groupId>
  <artifactId>jsr305</artifactId>
  <version>3.0.0</version>
  <classifier>sources</classifier>
</dependency>
```

Does that work for you?

**Comment by realityforge** [comment]
Closing as no response and likely a configuration issue
