### ISSUE TITLE
Issue with GWT 2.8.1

### ISSUE THREAD

**Issue by celerite** [realityforge/gwt-websockets#8]
When running this in GWT 2.8.1. When running from the browser in super dev mode I get the following:

com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'Dc' of null
	at Unknown.Bx(PlaceHistoryHandler.java:192)
	at Unknown.Nb(PlaceHistoryHandler.java:118)
	at Unknown.nw(com_00046celertech_00046cb_00046web_00046CBClient__EntryMethodHolder.java:3)
	at Unknown.h(ModuleUtils.java:44)
	at Unknown.Le(Impl.java:309)
	at Unknown.Oe(Impl.java:368)
	at Unknown.anonymous(Impl.java:78)
	at Unknown.dw(ModuleUtils.java:55)

"org.realityforge.gwt.websockets:gwt-websockets:1.2",

<inherits name="org.realityforge.gwt.websockets.WebSockets"/>

 final WebSocket socket = WebSocket.newWebSocketIfSupported();
	    socket.setListener(new WebSocketListenerAdapter() {

			@Override
		    public void onOpen( final WebSocket webSocket )
		    {
		      // After we have connected we can send
		      webSocket.send( "Hello!" );
		    }

		    @Override
		    public void onMessage( final WebSocket webSocket, final String data )
		    {
		      // After we receive a message back we can close the socket
		      webSocket.close();
		    }
	    });

**Comment by realityforge** [comment]
That exception looks unrelated to anything to do with the websocket library. The exception  seems to indicate you registered a null `PlaceController` in the PlaceHistoryHandler. If you have an example that illustrates a problem with this library. Feel free to re-open the issue and describe it in more detail

**Comment by celerite** [comment]
Issue is when I commet out the code the application loads without any issues so it did not look like the platceHistoryHandler.

**Comment by realityforge** [comment]
Okay - can not reproduce. It works fine for the sample project at https://github.com/realityforge/gwt-websockets-example which is GWT 2.8.1. If you can give me details how to reproduce it I can look at it ... but given your stack trace I think it is something to do with place configuration and unlikely related to this framework
